version: '3'
services:
  discord-bot:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DISCORD_BOT_TOKEN=""
      - CLOUDFLARE_API_TOKEN=""
    networks:
      - net
    restart: unless-stopped
    volumes:
     - .pyt:/app
networks:
      net:
       name: proxy_nginx
       external: true

